services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/ssd:/media
      - ./jellyfin-config:/config

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8080
    volumes:
      - /mnt/ssd/downloads:/downloads
      - ./qbittorrent-config:/config

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./site:/srv:ro

