services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/ssd:/media
      - ./jellyfin-config:/config

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8080
    volumes:
      - /mnt/ssd/downloads:/downloads
      - ./qbittorrent-config:/config

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv:ro

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    volumes:
      - /opt/server/sonarr-config:/config
      - /mnt/ssd/downloads:/downloads
      - /mnt/ssd/TV:/tv
    network_mode: host
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    volumes:
      - /opt/server/radarr-config:/config
      - /mnt/ssd/downloads:/downloads
      - /mnt/ssd/Movies:/movies
    network_mode: host
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    volumes:
      - /opt/server/jackett-config:/config
      - /mnt/ssd/downloads:/downloads    # optional, for indexer testing
    network_mode: host                  # so it can talk to qBittorrent on localhost
    restart: unless-stopped

