version: "3.8"
services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.49
    container_name: openhands-app
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.49-nikolaik
      - LOG_ALL_EVENTS=true
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/server/openhands:/.openhands
      - /opt/server/openhands_workspace:/opt/workspace_base
    pull_policy: always
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/ssd:/media
      - ./jellyfin-config:/config

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8080
    volumes:
      - /mnt/ssd/downloads:/downloads
      - ./qbittorrent-config:/config

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./site:/srv/site:ro
      - /mnt/ssd2:/mnt/ssd2:ro

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    volumes:
      - /opt/server/sonarr-config:/config
      - /mnt/ssd/downloads:/downloads
      - /mnt/ssd/TV:/tv
    network_mode: host
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    volumes:
      - /opt/server/radarr-config:/config
      - /mnt/ssd/downloads:/downloads
      - /mnt/ssd/Movies:/movies
    network_mode: host
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    volumes:
      - /opt/server/jackett-config:/config
      - /mnt/ssd/downloads:/downloads
    network_mode: host
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/server/portainer-data:/data
    ports:
      - 9000:9000
    restart: unless-stopped
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    ports:
      - 19999:19999
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  swabscan_qdrant:
    image: qdrant/qdrant:latest
    container_name: swabscan_qdrant
    restart: unless-stopped
    network_mode: host
    volumes:
      - swabscan_qdrant_data:/qdrant/storage

  swabscan_app:
    build:
      context: /opt/swabscan
      dockerfile: Dockerfile
    container_name: swabscan_app
    restart: unless-stopped
    network_mode: host           # Streamlit listens on 0.0.0.0:8501
    environment:
      QDRANT_URL: "http://127.0.0.1:6333"
    volumes:
      - /mnt/ssd2/pduddy:/app/input:ro
      - /opt/swabscan:/app


volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
  swabscan_qdrant_data:
    external: true
